#!/usr/bin/env python3
#
# Script to generate the multihash identifier registry from the CSV file
import codecs
import csv
import urllib.request

url = 'https://github.com/multiformats/multibase/blob/b9ca0426d9d1f8c4b7be6925e5b8be04cabe6ab9/multibase.csv'
stream = urllib.request.urlopen(url)
csvdata = csv.reader(codecs.iterdecode(stream, 'utf-8'))

print("""
      <texttable anchor="mf-registry-group" title="Multiformats Registry Group">
        <ttcol align="center">Name</ttcol>
        <ttcol align="center">Identifier</ttcol>
        <ttcol align="center">Status</ttcol>
        <ttcol align="center">Specification</ttcol>
""")

for line in csvdata:
    if line[1].strip() != 'multihash':
        continue

    codec = line[0].strip()
    identifier = line[2].strip()
    status = 'active'
    spec = 'Unknown'

    if(codec.startswith('blake2')):
        spec = '<xref target="RFC7693">RFC 7693</xref>'
    elif(codec.startswith('sha1')):
        spec = '<xref target="RFC6234">RFC 6234</xref>'
    elif(codec.startswith('sha2')):
        spec = '<xref target="RFC6234">RFC 6234</xref>'
    elif(codec.startswith('md4')):
        status = 'deprecated'
        spec = '<xref target="RFC6150">RFC 6150</xref>'
    elif(codec.startswith('md5')):
        status = 'deprecated'
        spec = '<xref target="RFC6151">RFC 6151</xref>'

    print(f'        <c>{codec}</c><c>{identifier}</c><c>{status}</c><c>{spec}</c>')

print('      </texttable>')
